# Sources : USDA - United States Department of Agriculture
#         : FAO - Food and Agriculture Organization

# USDA API Key
API : ''

# Year/Years
YEAR: 
 - 2015
 - 2016
 - 2017

# Variable_id - Refer to variables.csv to access the ids
id:
 - 'igovt'
 - 'evfertc'

# domain_id - Refer to domain.csv to access the codes
codes:
 - 'IG'
 - 'IC'
 - 'RFN'
 - 'RFB'