# Sources : USDA - United States Department of Agriculture
#         : FAO - Food and Agriculture Organization

# USDA API Key : Optional
API : ''

# Year/Years : Required
YEAR: 
 - 2015
 - 2016
 - 2017

# variable_id - Refer to variables.csv to access the ids : Required
id:
 - 'igovt'
 - 'evfertc'

# domain_id - Refer to domain.csv to access the codes : Required
codes:
 - 'IG'
 - 'IC'
 - 'RFN'
 - 'RFB'
